### ISSUE TITLE
Error connecting to Github while installing new project

### ISSUE THREAD

**Issue by mathamel** [lucky-media/cloud#18]
### Platform

Linux

### Browser

Google Chrome

### Describe the bug

```bash
While creating a new project with the starter-kit, I run into this issue
```

### Repo Steps

```bash
1. statamic new myproject lucky-media/cloud
2. error show
3. site is not working
```

### Expected Behavior

```bash
Installation should complete without issue.
```

### Anything else?

![Capture d’écran 2022-08-03 205230](https://user-images.githubusercontent.com/12539609/182739940-5f10f1b8-ceab-42e2-a629-036c8ad7df92.jpg)

**Comment by lokmanm** [comment]
Hi @mathamel,

From the error it looks like it failed to connect to the Github API.  Unfortunately this is not something we control or can help you out.

My suggestion would be to maybe try again ?
If the error persists you will have to report it to the Statamic team. This is CLI related so this [repo](https://github.com/statamic/cli) is the best option.

Let me know if I can help you in any other way.

Thanks!
